script: |
  cd ~/devops-autocloud || git clone https://github.com/nadiaim786/devops-autocloud.git ~/devops-autocloud
  cd ~/devops-autocloud

  git pull origin main

  docker stop app || true
  docker rm app || true

  # remove all old containers that might block port
  docker stop $(docker ps -q) || true
  docker rm $(docker ps -aq) || true

  # IMPORTANT: correct Dockerfile path
  docker build -t autocloud-app ./app

  docker run -d -p 3001:3000 --name app autocloud-app
